server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:stagiairedb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
  main:
    allow-bean-definition-overriding: true

  jpa:
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

  h2:
   console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

# JWT Configuration
app:
  jwt:
    secret: mysecretkey123456789012345678901234567890abcdefghijklmnopqrstuvwxyz
    expiration:
      ms: 86400000 # 24 hours

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method